<?php

Dict::Add('ES CR', 'Spanish', 'Español, Castellano', array(
	'Menu:DataSources' => 'Fuentes de Datos Sincronizables',
	'Menu:DataSources+' => 'Fuentes de Datos Sincronizables',
	'Menu:WelcomeMenu' => 'Bienvenido',
	'Menu:WelcomeMenu+' => 'Bienvenido a NT3',
	'Menu:WelcomeMenuPage' => 'Bienvenido',
	'Menu:WelcomeMenuPage+' => 'Bienvenido a NT3',
	'Menu:AdminTools' => 'Herramientas Administrativas',
	'Menu:AdminTools+' => 'Herramientas Administrativas',
	'Menu:AdminTools?' => 'Herramientas accesibles sólo a usuarios con Perfil de administrador',
	'Menu:DataModelMenu' => 'Modelo de Datos',
	'Menu:DataModelMenu+' => 'Resumen del Modelo de Datos',
	'Menu:ExportMenu' => 'Exportar',
	'Menu:ExportMenu+' => 'Exportar los Resultados de Cualquier Consulta en HTML, CSV o XML',
	'Menu:NotificationsMenu' => 'Notificaciones',
	'Menu:NotificationsMenu+' => 'Configuración de las Notificaciones',
	'Menu:AuditCategories' => 'Auditar Categorías',
	'Menu:AuditCategories+' => 'Auditar Categorías',
	'Menu:Notifications:Title' => 'Auditar Categorías',
	'Menu:RunQueriesMenu' => 'Ejecutar Consultas',
	'Menu:RunQueriesMenu+' => 'Ejecutar Cualquier Consulta',
	'Menu:QueryMenu' => 'Libreta de Consultas',
	'Menu:QueryMenu+' => 'Libreta de Consultas',
	'Menu:UniversalSearchMenu' => 'Búsqueda Universal',
	'Menu:UniversalSearchMenu+' => 'Buscar cualquier cosa',
	'Menu:UserManagementMenu' => 'Administración de Usuarios',
	'Menu:UserManagementMenu+' => 'Administración de Usuarios',
	'Menu:ProfilesMenu' => 'Perfiles',
	'Menu:ProfilesMenu+' => 'Perfiles',
	'Menu:ProfilesMenu:Title' => 'Perfiles',
	'Menu:UserAccountsMenu' => 'Cuentas de Usuario',
	'Menu:UserAccountsMenu+' => 'Cuentas de Usuario',
	'Menu:UserAccountsMenu:Title' => 'Cuentas de Usuario',
	'Menu:MyShortcuts' => 'Mis Accesos Rápidos',
));
