<?php

Dict::Add('IT IT', 'Italian', 'Italiano', array(
	'Menu:DataSources' => 'Sorgente di sincronizzazione dei dati',
	'Menu:DataSources+' => '',
	'Menu:WelcomeMenu' => 'Benveuto',
	'Menu:WelcomeMenu+' => '',
	'Menu:WelcomeMenuPage' => 'Benvenuto',
	'Menu:WelcomeMenuPage+' => '',
	'Menu:AdminTools' => 'Strumenti di amministrazione',
	'Menu:AdminTools+' => '',
	'Menu:AdminTools?' => 'Strumenti accessibile solo agli utenti con il profilo di amministratore',
	'Menu:DataModelMenu' => 'Modello Dati',
	'Menu:DataModelMenu+' => '',
	'Menu:ExportMenu' => 'Esporta',
	'Menu:ExportMenu+' => '',
	'Menu:NotificationsMenu' =>  'Notifiche',
	'Menu:NotificationsMenu+' => '',
	'Menu:AuditCategories' => 'Categorie di Audit',
	'Menu:AuditCategories+' => '',
	'Menu:Notifications:Title' => 'Categorie di Audit',
	'Menu:RunQueriesMenu' => 'Esegui query',
	'Menu:RunQueriesMenu+' => '',
	'Menu:UniversalSearchMenu' => 'Ricerca universale',
	'Menu:UniversalSearchMenu+' => '',
	'Menu:UserManagementMenu' => 'Gestione degli utenti',
	'Menu:UserManagementMenu+' => '',
	'Menu:ProfilesMenu' => 'Profili',
	'Menu:ProfilesMenu+' => '',
	'Menu:ProfilesMenu:Title' => 'Profili',
	'Menu:UserAccountsMenu' => 'Account utente',
	'Menu:UserAccountsMenu+' => '',
	'Menu:UserAccountsMenu:Title' => 'Account utente',
	'Menu:QueryMenu' => 'Query phrasebook~~',
	'Menu:QueryMenu+' => 'Query phrasebook~~',
	'Menu:MyShortcuts' => 'My Shortcuts~~',
));
