<?php

Dict::Add('HU HU', 'Hungarian', 'Magyar', array(
	'Menu:DataSources' => 'Szinkronizált adatforrások',
	'Menu:DataSources+' => '',
	'Menu:WelcomeMenu' => 'Üdvözlöm',
	'Menu:WelcomeMenu+' => '',
	'Menu:WelcomeMenuPage' => 'Üdvözlöm',
	'Menu:WelcomeMenuPage+' => '',
	'Menu:AdminTools' => 'Adminisztrációs eszközök',
	'Menu:AdminTools+' => '',
	'Menu:AdminTools?' => 'Eszközök csak az adminisztrátori profilhoz rendlet felhasználók számára elérhetők.',
	'Menu:DataModelMenu' => 'Adatmodell',
	'Menu:DataModelMenu+' => '',
	'Menu:ExportMenu' => 'Export',
	'Menu:ExportMenu+' => '',
	'Menu:NotificationsMenu' => 'Értesítések',
	'Menu:NotificationsMenu+' => '',
	'Menu:AuditCategories' => 'Audit kategóriák',
	'Menu:AuditCategories+' => '',
	'Menu:Notifications:Title' => 'Audit kategóriák',
	'Menu:RunQueriesMenu' => 'Lekérdezés futtatás',
	'Menu:RunQueriesMenu+' => '',
	'Menu:UniversalSearchMenu' => 'Univerzális keresés',
	'Menu:UniversalSearchMenu+' => '',
	'Menu:UserManagementMenu' => 'Felhasználó menedzsment',
	'Menu:UserManagementMenu+' => '',
	'Menu:ProfilesMenu' => 'Profilok',
	'Menu:ProfilesMenu+' => '',
	'Menu:ProfilesMenu:Title' => 'Profilok',
	'Menu:UserAccountsMenu' => 'Felhasználói fiókok',
	'Menu:UserAccountsMenu+' => '',
	'Menu:UserAccountsMenu:Title' => 'Felhasználói fiókok',
	'Menu:QueryMenu' => 'Query phrasebook~~',
	'Menu:QueryMenu+' => 'Query phrasebook~~',
	'Menu:MyShortcuts' => 'My Shortcuts~~',
));
