<?php

Dict::Add('TR TR', 'Turkish', 'Türkçe', array(
	'Menu:WelcomeMenu' => 'Hoşgeldiniz',
	'Menu:WelcomeMenu+' => 'NT3\'a Hoşgeldiniz',
	'Menu:WelcomeMenuPage' => 'Hoşgeldiniz',
	'Menu:WelcomeMenuPage+' => 'NT3\'a Hoşgeldiniz',
	'Menu:AdminTools' => 'Yönetim Araçları',
	'Menu:AdminTools+' => 'Yönetim Araçları',
	'Menu:AdminTools?' => 'Yönetici profiline izin verilen araçlar',
	'Menu:DataModelMenu' => 'Veri Modeli',
	'Menu:DataModelMenu+' => 'Veri Modeli Özeti',
	'Menu:ExportMenu' => 'Dışarı ver',
	'Menu:ExportMenu+' => 'Sorgu sonucunu HTML, CSV veya XML olarak dışarı aktar',
	'Menu:NotificationsMenu' => 'Uyarılar',
	'Menu:NotificationsMenu+' => 'Uyarıların yapılandırılması',
	'Menu:AuditCategories' => 'Denetleme Kategorileri',
	'Menu:AuditCategories+' => 'Denetleme Kategorileri',
	'Menu:Notifications:Title' => 'Denetleme Kategorileri',
	'Menu:RunQueriesMenu' => 'Sorgu çalıştır',
	'Menu:RunQueriesMenu+' => 'Sorgu çalıştır',
	'Menu:UniversalSearchMenu' => 'Genel sorgu',
	'Menu:UniversalSearchMenu+' => 'Herhangi bir arama...',
	'Menu:UserManagementMenu' => 'Kullanıcı Yönetimi',
	'Menu:UserManagementMenu+' => 'Kullanıcı Yönetimi',
	'Menu:ProfilesMenu' => 'Profiller',
	'Menu:ProfilesMenu+' => 'Profiller',
	'Menu:ProfilesMenu:Title' => 'Profiller',
	'Menu:UserAccountsMenu' => 'Kullanıcı Hesapları',
	'Menu:UserAccountsMenu+' => 'Kullanıcı Hesapları',
	'Menu:UserAccountsMenu:Title' => 'Kullanıcı Hesapları',
	'Menu:DataSources' => 'Synchronization Data Sources~~',
	'Menu:DataSources+' => 'All Synchronization Data Sources~~',
	'Menu:QueryMenu' => 'Query phrasebook~~',
	'Menu:QueryMenu+' => 'Query phrasebook~~',
	'Menu:MyShortcuts' => 'My Shortcuts~~',
));
