<?php

Dict::Add('ZH CN', 'Chinese', '简体中文', array(
	'Menu:WelcomeMenu' => '欢迎',
	'Menu:WelcomeMenu+' => '欢迎来到nt3',
	'Menu:WelcomeMenuPage' => '欢迎',
	'Menu:WelcomeMenuPage+' => '欢迎来到nt3',
	'Menu:AdminTools' => '管理工具',
	'Menu:AdminTools+' => '管理工具',
	'Menu:AdminTools?' => '具有系统管理员简档的用户才能获得的工具',
	'Menu:DataModelMenu' => '数据模型',
	'Menu:DataModelMenu+' => '数据模型概览',
	'Menu:ExportMenu' => '导出',
	'Menu:ExportMenu+' => '以HTML, CSV or XML格式导出任何查询的结果',
	'Menu:NotificationsMenu' => '通知',
	'Menu:NotificationsMenu+' => '通知的配置',
	'Menu:AuditCategories' => '审计类目',
	'Menu:AuditCategories+' => '审计类目',
	'Menu:Notifications:Title' => '审计类目',
	'Menu:RunQueriesMenu' => '运行查询',
	'Menu:RunQueriesMenu+' => '运行任何查询',
	'Menu:UniversalSearchMenu' => '通用搜索',
	'Menu:UniversalSearchMenu+' => '搜索所有...',
	'Menu:UserManagementMenu' => '用户管理',
	'Menu:UserManagementMenu+' => '用户管理',
	'Menu:ProfilesMenu' => '简档',
	'Menu:ProfilesMenu+' => '简档',
	'Menu:ProfilesMenu:Title' => '简档',
	'Menu:UserAccountsMenu' => '用户帐户',
	'Menu:UserAccountsMenu+' => '用户帐户',
	'Menu:UserAccountsMenu:Title' => '用户帐户',
	'Menu:DataSources' => 'Synchronization Data Sources~~',
	'Menu:DataSources+' => 'All Synchronization Data Sources~~',
	'Menu:QueryMenu' => 'Query phrasebook~~',
	'Menu:QueryMenu+' => 'Query phrasebook~~',
	'Menu:MyShortcuts' => 'My Shortcuts~~',
));
